# Generated by Django 5.2.12 on 2026-04-06 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('processed_wav', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('dubbed_audio', models.FileField(blank=True, null=True, upload_to='dubbed/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('preprocessing', 'Preprocessing'), ('diarizing', 'Diarizing'), ('transcribing', 'Transcribing'), ('translating', 'Translating'), ('synthesizing', 'Synthesizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('progress', models.IntegerField(default=0)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('num_speakers', models.IntegerField(blank=True, null=True)),
                ('max_speakers', models.IntegerField(default=4)),
                ('transcript', models.JSONField(blank=True, null=True)),
                ('speaker_profiles', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
